### ISSUE TITLE
Upload to Pursuit

### ISSUE THREAD

**Issue by menelaos** [purescript-contrib/purescript-form-urlencoded#4]
Currently, `purescript-form-urlencoded` cannot be found via [Pursuit](https://pursuit.purescript.org/).

**Comment by garyb** [comment]
Pursuit needs updating first: purescript/pursuit#219 and all of the libraries will need re-uploading once that is done.

**Comment by zudov** [comment]
Uploaded it: https://pursuit.purescript.org/packages/purescript-form-urlencoded
