### ISSUE TITLE
Not compatible yet with purs 0.11.6-dev it seems?

### ISSUE THREAD

**Issue by metaleap** [purescript-contrib/purescript-form-urlencoded#8]
Using `purs` current `master` branch (prints `--version` as `0.11.6 dev build`), attempting to `pulp build` a project with `purescript-form-urlencoded` (got version 3.0.0 from Pursuit) in the deps results in:

    * Building project in /home/rox/c/ps/test-pscorefn-src
    Compiling Data.FormURLEncoded
    Error found:
    at bower_components/purescript-form-urlencoded/src/Data/FormURLEncoded.purs line 31, column 8 - line 31, column 64
    
      Cannot derive a type class instance for
                                           
        Data.Generic.Generic FormURLEncoded
                                           
      since instances of this type class are not derivable.

**Comment by zudov** [comment]
Hi, it is compatible with 0.11 release, and I've just tested it against [0.11.6](https://github.com/purescript/purescript/releases) (the idea is that 0.11.* releases don't contain breaking changes).

The master branch of a compiler contains breaking things that would go into next release. The one in question is https://github.com/purescript/purescript/pull/3007 it will be released as `0.12` or `1.0`. Thanks for an update, we'll need to update it at some point.

Do you badly need to use it with `master` compiler? The change is just about dropping [that line](https://github.com/purescript-contrib/purescript-form-urlencoded/blob/master/src/Data/FormURLEncoded.purs#L31).

**Comment by metaleap** [comment]
Thanks for explaining! Nothing urgent, no. Hadn't fully informed myself about how purs does its versioning and branching, it seems =) just using the master as I have a PR hanging in there that I do need. But to be perfectly honest I don't need to use form-urlencoded per se, just working on language-level tooling where I did go through most of Pursuit and used what compiled as my test-bench, while sending off a quick remark to the few projects that wouldn't compile under that in-flux forth-coming future purs  =)
